version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql_database:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  web:
    build: .
    restart: always
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  mysql_database: