version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - '2717:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  web:
    build: .
    restart: always
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - mongo