# Generated by Django 3.2.3 on 2021-06-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
