# Generated by Django 3.2.3 on 2021-05-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=32)),
                ('tag', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('story', models.CharField(max_length=1000)),
            ],
        ),
    ]
