name: Android CI/CD

on:
  push:
    branches: [ android ]
  pull_request:
    branches: [ android ]

jobs:
 test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: postory/android/Postory
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Unit tests
      run: bash ./gradlew test --stacktrace
      
    - name: ui tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 26
        target: default
        arch: x86
        profile: Nexus 6
        script:  postory/android/Postory/gradlew connectedCheck --stacktrace
  
 apk:
  name: Generate APK
  needs: test-build
  runs-on: ubuntu-latest
  steps:
   - name: Build debug APK
     run: bash ./gradlew assembleDebug --stacktrace
   - name: Upload APK
     uses: actions/upload-artifact@v2
     with:
       name: apk
       path:  postory/android/Postory/app/build/outputs/apk/debug/app-debug.apk
